### ISSUE TITLE
Long loading times, flickering

### ISSUE THREAD

**Issue by sauerj** [AngeloStavrow/indigo#23]
On https://themes.gohugo.io/theme/indigo/ the loading time is quite long and the site text is flickering.

I think this is caused by HTTP 404 error during loading the fonts. On a private test site I notice this too but then it is caused by the quite big fonts `FiraSans-Book.ttf` and `FiraSans-Bold.ttf`

~~I noticed that many links to images, fonts are absolute instead of relative links.~~
I noticed that many links to images, fonts are _relative_ instead of _absolute_ links.
Maybe it is necessary to make the links relative with a `{{ .Site.BaseURL }}` in front to get the correct path.

Edit: Actually I meant the opposite of what I wrote.

**Comment by sauerj** [comment]
![indigo-font-404](https://user-images.githubusercontent.com/14033792/47109152-d1dc7180-d24d-11e8-926c-4f1b1ca5c173.png)

First the text is rendered with a system font and then re-rendered. Same issue on [Netflify](xenodochial-beaver-f9b778.netlify.com.)

**Comment by AngeloStavrow** [comment]
Interesting. Do you see the fonts being loaded on the demo site? Or is it reverting to the fallbacks?

**Comment by sauerj** [comment]
I believe that it is reverting to the fallbacks on the demo site, but I am not 100% sure. On the linked site to my test page on netlify the fonts are correctly loaded but I can see flickering when the site changes to the correct fonts.

**Comment by sauerj** [comment]
To be clear, the flickering only appears with an empty cache. On the demo site on every reload.

**Comment by AngeloStavrow** [comment]
@sauerj There's a separate [issue in the theme gallery demo site](https://github.com/gohugoio/hugoThemes/issues/442#issuecomment-430350304) where fonts aren't loading correctly. I'm trying to track that down.

On the other hand, I believe the 'flickering' you're referring to might be what's known as the "Flash Of Invisible Text" (FOIT) or, with some browsers, the "Flash Of Unstyled Text" (FOUT), where the browser either waits until the font is loaded to display content, or shows unstyled content.

There are [ways around this](https://css-tricks.com/fout-foit-foft/), but they require JavaScript or poorly-supported CSS properties. I think you might be on to something with the size of some of the bundled fonts (some of these TTF fonts are close to a half-megabyte in size), and they're included for the deepest browser support.

What I _did_ find, however, was that the way these `@font-face`s (except the latest addition of Fira Code) were listed in the stylesheet was wrong, such that the browser would load the last option on the list for each font—and that was almost always the TTF font. I've fixed this now, and added [`font-display: optional`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) for each — there's limited browser support for this, but where it is supported, it should work best for slow connections.

(I also made sure that there are reasonable fallbacks for all fonts in the stylesheet — I was seeing **serif** in codeblocks instead of **monospace** and that's just terrible.)
